### PR TITLE
Add the docformatter pre commit hook to not have PR tainted by unwant…

### PR DESCRIPTION
**Pull request by ale-rt**
…ed commits on the docstrings

### CODE REVIEW

**Comment by ale-rt** [comment]
I am not a fun of this solution but it seems necessary

**Review by thet — APPROVED** [review]
Why is it necessary - do you also have docformatter insalled for your IDE? I have and I do like the docformatter but I‌ also have these formatting issues when saving in my IDE.

The problem with docformatter is that it is currently incompatible with black:
https://github.com/PyCQA/docformatter/issues/94

Therefore I will approve and merge but add another PR to deactivate the docformatter again. OK?

**Comment by ale-rt** [comment]
I do not use it.
The main goal is to not have spurious changes in the patches.

**Comment by thet** [comment]
OK, let's keep it. I was trying this pre-commit hook and it currently does not clash with black and it seems all fine.
As soon as it makes any troubles we can just remove it again and I will deactivate `docformatter` from my editor's toolset.

**Pull request merged**
